[battery]
disabled = true

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[✗](bold red) "

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
read_only = " "

[c]
detect_extensions = ["c"]
